### ISSUE TITLE
Component for MacOS

### ISSUE THREAD

**Issue by pnck** [pnck/foo_input_ncm#1]
According to [the official site](https://www.foobar2000.org/mac) and [the discussion](https://hydrogenaud.io/index.php?topic=124799.msg1033246#msg1033246), fb2k for Mac should have supported _component_ / _addon_ feature.

SDK should be bumped to a newer version and Mac support should be considered.

**Comment by PhyX-Meow** [comment]
And also, could the x64 version be added? For using with foobar2000 2.0 64bit.

**Comment by pnck** [comment]
> And also, could the x64 version be added? For using with foobar2000 2.0 64bit.

Sure. I'll manage to introduce multiple target build pipelines.

**Comment by pnck** [comment]
@PhyX-Meow 

The multiplatform component is now released. Please check the [release page](https://github.com/pnck/foo_input_ncm/releases/latest).

**Comment by PhyX-Meow** [comment]
@pnck Great work! Thank you!
