### ISSUE TITLE
下载的专辑部分歌曲可播放，部分歌曲无法添加到播放列表，无法播放

### ISSUE THREAD

**Issue by xdugit** [pnck/foo_input_ncm#11]
foobar2000 版本： v2.1.5 [x64]
云音乐 版本：3.0.0.Beta(64位)(Build: 202739)Patch:36c5d65
ncm插件版本：0.5.0
问题：
从如下网址下载的专辑，https://music.163.com/album?id=16010&userid=1684945629
其中《晴雯歌》可以播放，《分骨肉》不可播放。
附上这两首歌以供分析。
[ncm.zip](https://github.com/pnck/foo_input_ncm/files/15288919/ncm.zip)

**Comment by pnck** [comment]
可以复现，请再补充一下下载的时候的相关信息：

- 下载时 NCM 的版本和平台
- 会员状态： vip/svip
- 音质选择

**Comment by pnck** [comment]
Meta JSON: 
```js
{
  "musicId": "159431",
  "musicName": "***",
  "artist": [
    [
      "陈力",
      "7461"
    ]
  ],
  "albumId": "16010",
  "album": "***",
  "albumPicDocId": "43980465112063",
  "albumPic": "https://p3.music.126.net/phLRtDb24dkUkQHEzDhQZw==/43980465112063.jpg",
  "bitrate": 320000,
  "mp3DocId": "15d6d5447ff4e82c277ccae3590c650f",
  "duration": 285000,
  "mvId": "", // <= empty string
  "alias": [],
  "transNames": [],
  "format": "mp3",
  "fee": 8,
  "volumeDelta": -0.8592,
  "privilege": {
    "flag": 1343492
  }
}
```

**Comment by xdugit** [comment]
> 可以复现，请再补充一下下载的时候的相关信息：
> 
> * 下载时 NCM 的版本和平台
> * 会员状态： vip/svip
> * 音质选择

下载时 NCM 的版本和平台：3.0.0.Beta(64位)(Build: 202739)Patch:36c5d65，Windows 11 X64
会员状态： vip
音质选择：极好
