### ISSUE TITLE
部分歌曲无法被识别到

### ISSUE THREAD

**Issue by yfeng445** [pnck/foo_input_ncm#13]
在将整个文件夹添加到播放列表后, 有一些歌曲看不到. 
尝试手动添加文件, 但是添加后依然无法在列表中找到. 
在使用ncmdump将文件转为flac格式后添加到播放列表, 添加成功
![微信截图_20240731153253](https://github.com/user-attachments/assets/2a82a1ca-39ab-40bc-93c6-aae941cd331a)
![微信截图_20240731153349](https://github.com/user-attachments/assets/46fe34c1-444f-4fe3-88cd-85ff68863481)

**Comment by pnck** [comment]
通常是 metadata 又有一些奇怪的以前没观察到的字段造成的，麻烦提供一下样本文件

**Comment by yfeng445** [comment]
> 通常是 metadata 又有一些奇怪的以前没观察到的字段造成的，麻烦提供一下样本文件

https://drive.google.com/file/d/1G5wTBuS6tpNeHmiwwU_dvnfTILa0aFVV/view?usp=sharing
这是文件链接

**Comment by pnck** [comment]
已有线索，大概周末能抽个时间修

**Comment by LuiScreaMed** [comment]
发现新下载的ncm文件头是flac，但是缺失歌曲信息了😭

**Comment by jonathan-tw** [comment]
我這裡有發現舊的cloudmusic.dll也失效了，mp3與flac皆缺失歌曲信息

> 发现新下载的ncm文件头是flac，但是缺失歌曲信息了😭

**Comment by pnck** [comment]
Should have been fixed at v0.5.2
