### ISSUE TITLE
Cannot loaded in V2.1.5 

### ISSUE THREAD

**Issue by eego5869** [pnck/foo_input_ncm#14]
![image](https://github.com/user-attachments/assets/4459878c-1137-41b8-90f9-f58fb2923a03)
![image](https://github.com/user-attachments/assets/a6259ef1-6553-4e1c-a117-f6d337c2c03e)

os：windows server 2022

**Comment by bWFuanVzYWth** [comment]
fb2k v2.1.6 同样无法加载 dll 0.5.2，但是可以用0.5.1

**Comment by pnck** [comment]
提供一下信息，暂时没时间修：
- fb2k 更新了sdk，会导致 win和mac平台现在都会编译出无效的动态库，原因暂时没空深究，似乎会链接错误的runtime库
- 不知为何，用旧版的sdk也会出现这种现象
- 0.5.2 比 0.5.1 只是修复了一点弱类型meta信息导致的无法解析的问题，如果自己的歌单里没有播放不了的曲目文件可以先不管

**Comment by pnck** [comment]
v0.5.3 修复
